#!/usr/bin/env bash
# tests/check_layout.sh — every config file is where its lifecycle says, and nothing is a leftover.
#
# The layout rule (profiles/README.md) is that a file's DIRECTORY answers "is
# this running?": prompts/ and profiles/directives/ and arms/ are live,
# profiles/offline/ is inert until you name it. A rule like that is worth
# nothing unwatched — it decays one retired arm at a time, and the decay is
# invisible precisely because a stale file looks exactly like a live one.
#
# So this test asserts, from the RESOLVED configuration rather than from the
# tree:
#   1. no ORPHAN rows in `bin/brief.sh --files` — nothing in a live directory
#      that nothing points at
#   2. nothing live reaches into profiles/offline/ (the sandbox-only directives
#      are in there; GATE_MODE=report lives one careless path away)
#   3. nothing in profiles/offline/ points back out into the live directories
#   4. every active arm in the registry still has its file, and vice versa
#   5. a bare profile name still resolves after the move, from either directory,
#      with the live one winning — which is what bin/ab.sh's .exp variants rely on
#   6. every .exp variant names a profile that resolves
set -u
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO="$PWD"
fail=0
err() { printf 'LAYOUT FAIL: %s\n' "$*" >&2; fail=1; }
ok()  { printf '  ok  %s\n' "$*"; }

# The inventory is generated by brief.sh from the same resolution a run uses, so
# this test cannot pass by agreeing with a hand-written list. It runs BEFORE this
# script sources lib/config.sh, deliberately: sourcing exports base.env's keys
# into the environment, and the environment outranks an arm's own file — so a
# brief.sh spawned afterwards would report every arm as identical to the base.
INV="$(bash bin/brief.sh --files)" || { err "bin/brief.sh --files failed"; INV=""; }

# 1. no orphans
orphans="$(printf '%s\n' "$INV" | awk -F'\t' '$1 == "ORPHAN" { printf "  %s — %s\n", $2, $3 }')"
if [ -n "$orphans" ]; then
  err "file(s) in a live directory that nothing points at:
$orphans
  Delete them (git keeps them) or point something at them."
else
  ok "no orphaned directives, overlays or arm files"
fi

# 2. nothing live points into profiles/offline/
bad="$(printf '%s\n' "$INV" | awk -F'\t' '$1 == "LIVE" && $2 ~ /^profiles\/offline\// { print "  " $2 " — " $3 }')"
if [ -n "$bad" ]; then
  err "live configuration reaches into profiles/offline/:
$bad
  Those are sandbox-only. bin/arm.sh promote is how something becomes live."
else
  ok "nothing live reaches into profiles/offline/"
fi

# 3. …and nothing offline points back out. An offline profile that borrowed the
# base's directive would make the offline directory a liar in the other
# direction: editing a live file would then change an experiment silently.
bad=""
for f in profiles/offline/*.env; do
  [ -e "$f" ] || continue
  hits="$(grep -nE 'profiles/(directives|overlays)/' "$f" || true)"
  [ -z "$hits" ] || bad="$bad
  $f: $hits"
done
if [ -n "$bad" ]; then
  err "offline profile(s) pointing at a live directive or overlay:$bad"
else
  ok "profiles/offline/ points only at its own files"
fi

# 4. the registry and arms/ agree. promote and retire delete the file, so the two
# can only disagree if something went wrong or a file was hand-edited.
# shellcheck source=../lib/config.sh
. lib/config.sh
missing=""
while IFS= read -r a; do
  [ -n "$a" ] || continue
  [ -f "arms/$a.env" ] || missing="$missing $a"
done < <(blog_active_arms)
if [ -n "$missing" ]; then
  err "arm(s) marked active in logs/arms.tsv with no arms/<name>.env:$missing
  They will fail at run time. Either recreate the file or set the row retired."
else
  ok "every active arm has its file (leftovers are covered by check 1)"
fi

# 5. bare-name profile resolution, both directories, live winning. This is the
# seam the move introduced: an .exp says `VARIANT_loose_PROFILE=curator-loose`
# and must not care which directory holds the file.
got="$(blog_resolve_profile curator-loose)"
[ "$got" = "$REPO/profiles/offline/curator-loose.env" ] \
  || err "bare name did not resolve into profiles/offline/: got $got"
got="$(blog_resolve_profile default)"
[ "$got" = "$REPO/profiles/default.env" ] \
  || err "bare name did not resolve in profiles/: got $got"
# A name present in BOTH must resolve to the live one, or an experiment could be
# shadowed by a sandbox file of the same name.
tmpname="layouttest$$"
printf 'MAX_NEW=1\n' > "profiles/$tmpname.env"
printf 'MAX_NEW=2\n' > "profiles/offline/$tmpname.env"
got="$(blog_resolve_profile "$tmpname")"
[ "$got" = "$REPO/profiles/$tmpname.env" ] \
  || err "profiles/ must outrank profiles/offline/ for the same name: got $got"
rm -f "profiles/$tmpname.env" "profiles/offline/$tmpname.env"
ok "bare profile names resolve in profiles/ then profiles/offline/"

# 6. every experiment definition still names a profile that exists
bad=""
for e in eval/experiments/*.exp; do
  [ -e "$e" ] || continue
  while IFS= read -r p; do
    [ -n "$p" ] || continue
    [ -f "$(blog_resolve_profile "$p")" ] || bad="$bad
  $(basename "$e"): $p"
  done < <(sed -n 's/^VARIANT_[A-Za-z0-9_]*_PROFILE=//p' "$e")
done
if [ -n "$bad" ]; then
  err "experiment variant(s) naming a profile that does not resolve:$bad"
else
  ok "every .exp variant's profile resolves"
fi

[ "$fail" -eq 0 ] || exit 1
echo 'layout check: OK'
